spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.121/SITM
    username: sitm_adm
    password: usradmin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true